const String termsAndConditions = '''
Terms and Conditions

Last Updated: [Date]

Welcome to thebighowl ("Website") and Howler ("App"). These Terms and Conditions ("Terms") govern your use of our digital billing service. By accessing or using the Website or App, you agree to comply with these Terms. If you disagree with any part, please refrain from using our services.

1. Introduction

Howler provides digital billing solutions that reduce paper waste and make billing information accessible and convenient. The App allows users to receive, view, and manage digital bills through unique codes ("HowlID") generated by participating merchants.

2. Acceptance of Terms

By accessing the Website or App, you agree to abide by these Terms and our Privacy Policy. We may periodically update these Terms, and your continued use of our services constitutes acceptance of those changes.

3. Use of the App

- Eligibility: You must be at least 18 years old or have parental consent.
- License: We grant you a limited, non-exclusive, non-transferable license to use Howler for its intended purpose.
- Restrictions: You agree not to misuse the App, attempt unauthorized access, or interfere with its functionality.

4. User Accounts and Security

- Account Creation: You may need to create an account on Howler to access certain features. You agree to provide accurate information and secure your account.
- Responsibility: You are responsible for all activity under your account. Notify us immediately of any unauthorized use.

5. HowlID and Digital Bill Management

- HowlID and Bill Access: HowlID is a unique code for accessing digital bills from partnered merchants. thebighowl and Howler are not liable for the accuracy of bill information provided by third parties.
- Data Storage: We store digital bills securely but do not guarantee indefinite retention. Users are encouraged to save copies as needed.

6. Data Protection and Privacy

We respect your privacy and comply with the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 under the Information Technology Act, 2000. Our Privacy Policy explains our data collection and use practices. By using Howler, you consent to these practices.

7. User Conduct

By using the Website or App, you agree not to:
- Violate applicable laws or third-party rights.
- Impersonate others or provide false information.
- Engage in conduct that disrupts other users or merchants.
- Attempt to hack, disrupt, or interfere with our services.

8. Intellectual Property

All intellectual property rights in thebighowl, Howler, and HowlID are owned by [Your Company Name]. You may not reproduce, modify, or distribute any part of our services without permission.

9. Limitations of Liability

- Service Availability: We do not guarantee continuous availability of Howler or thebighowl and may modify or discontinue services at any time.
- Accuracy of Digital Bills: [Your Company Name] is not liable for inaccuracies in digital bills provided by merchants.
- General Limitation: To the extent permitted by law, [Your Company Name] is not liable for damages from your use or inability to use our services.

10. Digital Payment Security

If digital payments are involved, Howler complies with the Reserve Bank of India’s (RBI) guidelines for secure digital transactions. We recommend users adopt secure payment practices.

11. Consumer Protection

We adhere to the Consumer Protection Act, 2019 and are committed to fair practices. If you have concerns about our services, please reach out to our support team at [Contact Information].

12. Third-Party Links and Services

Our services may contain links to third-party websites. thebighowl and Howler are not responsible for the content of these third-party sites and recommend reviewing their policies separately.

13. Indemnification

You agree to indemnify and hold harmless [Your Company Name], its employees, and affiliates from any claims, damages, liabilities, or expenses arising from your use of Howler, your violation of these Terms, or your violation of any third-party rights.

14. Termination

We reserve the right to terminate or restrict your access to Howler if you violate these Terms or engage in inappropriate conduct.

15. Governing Law and Jurisdiction

These Terms are governed by the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in Chennai, Tamil Nadu.

16. Language and Accessibility

These Terms are available in English. For translation or accessibility requests, please contact us at [Contact Information].

17. Contact Us

If you have questions or concerns regarding these Terms, please contact us:

Email: [Your Contact Email]
Phone: [Your Contact Number]
Address: [Your Company Address, Chennai, India]

Acceptance of Terms
By using Howler and thebighowl, you acknowledge that you have read, understood, and agree to these Terms and Conditions.
''';
