// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDucUeiGcIjqDAgPYrM2-uAJiZBounlPaI',
    appId: '1:201712669612:web:07e1bd278697fb719ba009',
    messagingSenderId: '201712669612',
    projectId: 'truepon-696cc',
    authDomain: 'truepon-696cc.firebaseapp.com',
    storageBucket: 'truepon-696cc.appspot.com',
    measurementId: 'G-35HVET0YCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMZK9Z60dxkzKzf0YwzxD5VL1OLt3EUcc',
    appId: '1:201712669612:android:abc1abbc3e0f760b9ba009',
    messagingSenderId: '201712669612',
    projectId: 'truepon-696cc',
    storageBucket: 'truepon-696cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3MjA2Bb0QRclwyaZr-WsUkIBh0GaiylQ',
    appId: '1:201712669612:ios:dd0a442cab51d88e9ba009',
    messagingSenderId: '201712669612',
    projectId: 'truepon-696cc',
    storageBucket: 'truepon-696cc.appspot.com',
    androidClientId: '201712669612-m3up99tlnkjqomgn0eue1fke1q0o98e7.apps.googleusercontent.com',
    iosClientId: '201712669612-bu7407auq2jt4b0pjnpf99tp96opc55f.apps.googleusercontent.com',
    iosBundleId: 'com.example.adsApp',
  );
}
